=== bojannrt9818/ist2021/projekatIST.dtd
<!ELEMENT VebProdavnica (Proizvod)*>
<!ATTLIST VebProdavnica
		xmlns CDATA #REQUIRED>
<!ELEMENT Proizvod (Kategorija|Cena|Oglas|Akcija)*>
<!ELEMENT Kategorija (#PCDATA)>
<!ELEMENT Cena (iznos)*>
<!ATTLIST Cena
		valuta CDATA #REQUIRED>
<!ELEMENT iznos (#PCDATA)>
<!ELEMENT Oglas (TekstOglasa|Tag)*>
<!ELEMENT TekstOglasa (#PCDATA)>
<!ELEMENT Tag (#PCDATA)>
<!ELEMENT Akcija (#PCDATA)>
<!ATTLIST Akcija
		Cena CDATA #REQUIRED
		DatumIsteka CDATA #REQUIRED>

=== bojannrt9818/ist2021/proizvodi.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE VebProdavnica SYSTEM "projekatIST.dtd">
<VebProdavnica>
  <Proizvod>
    <Kategorija>laptopovi</Kategorija>
    <Cena valuta="RSD">
      <iznos>56369.99</iznos>
    </Cena>
    <Oglas>
      <TekstOglasa>TekstOglasa1</TekstOglasa>
      <Tag>Računar</Tag>
      <Tag>Tehnika</Tag>
      <Tag>Samsung</Tag>
    </Oglas>
    <Akcija Cena="55000.00" DatumIsteka="2021-02-12" />
    <Akcija Cena="56369.23" DatumIsteka="2021-04-29" />
  </Proizvod>
  <Proizvod>
    <Kategorija>monitori</Kategorija>
    <Cena valuta="RSD">
      <iznos>12569.25</iznos>
    </Cena>
    <Oglas>
      <TekstOglasa>TekstOglasa1</TekstOglasa>
      <Tag>Računar</Tag>
      <Tag>Tehnika</Tag>
      <Tag>Samsung</Tag>
    </Oglas>
  </Proizvod>
  <Proizvod>
    <Kategorija>stolovi</Kategorija>
    <Cena valuta="RSD">
      <iznos>56369.23</iznos>
    </Cena>
    <Oglas>
      <TekstOglasa>TekstOglasa1</TekstOglasa>
      <Tag>Računar</Tag>
      <Tag>Tehnika</Tag>
      <Tag>Samsung</Tag>
    </Oglas>
    <Akcija Cena="125000.00" DatumIsteka="2021-02-26" />
  </Proizvod>
</VebProdavnica>
